artifact_location: file:///C:/Users/rohan/OneDrive/Desktop/MLops/first_demo/mlruns/0
creation_time: 1722887221309
experiment_id: '0'
last_update_time: 1722887221309
lifecycle_stage: active
name: Default
